BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

-- INSERT brewery

INSERT INTO brewery (name, location, established_year, description, imageURL, mapURL, longitude, latitude) VALUES
('Hoof Hearted Brewery and Kitchen', '850 N 4th St, Columbus, OH 43215', 2011, 'Quirky brewery & restaurant offering craft beers, inventive pub fare & a large patio.','https://images.squarespace-cdn.com/content/v1/530fa82ae4b059649e4b5d3c/1394423334322-L2RLZT2CSZEFC4S7XDTI/HHB_ROUND_flat_RGB.jpg?format=1500w', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3057.251963376068!2d-83.00065082419543!3d39.98047427151304!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388ed3fe9f69d1%3A0x1fb02f69eba443e1!2sHoof%20Hearted%20Brewery%20and%20Kitchen!5e0!3m2!1sen!2sus!4v1713208195595!5m2!1sen!2sus',CAST(-82.998009 AS DECIMAL(10, 6)),CAST(39.980068 AS DECIMAL(10, 6))),
('Wolfs Ridge Brewing', '215 N 4th St, Columbus, OH 43215', 2013, 'Modern brewpub serving a range of craft beers & elevated pub fare in a sleek, industrial setting.', 'https://i0.wp.com/www.dublinarts.org/wp-content/uploads/2016/10/WRB-Element_02LogoWolf.png?fit=2400%2C2400&ssl=1','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d24462.52699608176!2d-83.05841504181831!3d39.96786917694444!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388f2c353c2bdd%3A0x28b696ba7106a90!2sWolf;s%20Ridge%20Brewing!5e0!3m2!1sen!2sus!4v1713208249245!5m2!1sen!2sus',CAST(-82.997353 AS DECIMAL(10, 6)) ,CAST(39.967312 AS DECIMAL(10, 6))),
('Knotty Pine Brewing', '1765 W 3rd Ave, Columbus, OH 43212', 2017, 'Brewpub serving housemade craft beers & American eats in a cozy space with a woodsy vibe.', 'https://img.cdn4dd.com/cdn-cgi/image/fit=contain,width=1200,height=672,format=auto/https://doordash-static.s3.amazonaws.com/media/restaurant/cover_square/b3b1bcfa-578c-44fe-afbd-0e7be697a034.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3057.037201431978!2d-83.05552092419516!3d39.98527397151228!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388e492fe8207f%3A0xde42b5db95f33551!2sKnotty%20Pine%20Brewing!5e0!3m2!1sen!2sus!4v1713208298094!5m2!1sen!2sus', CAST(-83.052963 AS DECIMAL(10, 6)), CAST(39.985340 AS DECIMAL(10, 6))),
('Barleys Brewing Company', '467 N High St, Columbus, OH 43215', 1992, 'Longtime brewpub serving housemade beers & classic pub fare in a cozy, brick-walled space.', 'https://popmenucloud.com/apxqvlfc/a2ee7f33-6b54-4193-b5c1-6da023bc3221.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3057.6351409227395!2d-83.00547072419586!3d39.9719094715146!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388f289220bced%3A0xea496178b8e8bce6!2sBarley;s%20Brewing%20Company!5e0!3m2!1sen!2sus!4v1713208843827!5m2!1sen!2sus', CAST(-83.002808 AS DECIMAL(10, 6)) , CAST(39.971920 AS DECIMAL(10, 6))),
('Columbus Brewing Company', '2555 Harrison Rd, Columbus, OH 43204', 1988, 'Columbus Brewing Company is an independent craft brewery dedicated to exploring the flavors of American hops. Best known for Columbus IPA and Bodhi.', 'https://beerpulse.com/wp-content/uploads/2011/02/CBC_CMYK_square_burgandy_sm.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48925.377467960294!2d-83.14548385136723!3d39.96741719999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388fdac1305edb%3A0x6a88bcef9bbd49e4!2sColumbus%20Brewing%20Company!5e0!3m2!1sen!2sus!4v1713208929788!5m2!1sen!2sus',CAST(-83.069710 AS DECIMAL(10, 6)), CAST(39.967640 AS DECIMAL(10, 6))),
('Olentangy River Brewing Company', '303 Green Meadows Dr S, Lewis Center, OH 43035', 2008, 'Olentangy River Brewing Company, nestled in Ohio, offers a vibrant array of handcrafted brews, reflecting the regions spirit and heritage, all within a welcoming and community-focused atmosphere.', 'https://images.squarespace-cdn.com/content/v1/6192e85d8c6bc27fc2530eec/473350b2-03fb-4fd4-855e-2783d465337c/Logo_Badge.png?format=1500w', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3049.409447249634!2d-83.0150228241863!3d40.1554365714828!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8838f395ceefffff%3A0xb4503eb1b1af7c54!2sOlentangy%20River%20Brewing%20Company!5e0!3m2!1sen!2sus!4v1713208993035!5m2!1sen!2sus', CAST(-83.012510 AS DECIMAL(10, 6)), CAST(40.155400 AS DECIMAL(10, 6))),
('Thunderwing Brewing Company', '2419 Scioto Harper Dr, Columbus, OH 43204', 2023, 'Thunderwing Brewing is an American Craft brewery which is operating out of the west side of Columbus . Focusing on a wide variety of offerings, from light easy drinkers, to dark robust ales with plenty of hoppy options as well!', 'https://thunderwingbrewing.com/wp-content/uploads/2023/07/ThunderWing-Full-1.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3057.8617100103256!2d-83.06951082419613!3d39.96684447151542!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388fbcd3b4a447%3A0xa2ff98361ecd063d!2sThunderwing%20Brewing!5e0!3m2!1sen!2sus!4v1713209034839!5m2!1sen!2sus', CAST(39.967010 AS DECIMAL(10, 6)), CAST(-83.066930 AS DECIMAL(10, 6))),
('Seventh Son Brewing Co', '1101 N 4th St, Columbus, OH 43201', 2013, 'Comfortable tap room and patio with a rotating schedule of food trucks. Since April of 2013 Seventh Son has brewed over 225 different beers and has been consistently voted Columbus best brewery', 'https://drinkupcolumbus.com/wp-content/uploads/2012/04/seventh-son.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3057.0332189361166!2d-83.00226972419512!3d39.985362971512195!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388ece1e570549%3A0x76d37b7748664e44!2sSeventh%20Son%20Brewing%20Co.!5e0!3m2!1sen!2sus!4v1713209098885!5m2!1sen!2sus', CAST(-82.999649 AS DECIMAL(10, 6)), CAST(39.985329 AS DECIMAL(10, 6))),
('DankHouse Brewing Company', '161 Forry St, Newark OH 43055', 2017, 'We specialize in IPAs, stouts, and fruited kettle sours. We were named as one of the countrys top 12 new breweries of 2018 by the team at Hop Culture.', 'https://i.pinimg.com/736x/95/93/87/959387bc9d87dcd2dd341fc35fe6b553.jpg', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d97741.06832193231!2d-82.500945488157!3d40.043986415661074!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x883817c655c3170b%3A0x8aa0c4b030d38153!2sDankHouse%20Brewing%20Company!5e0!3m2!1sen!2sus!4v1713398727201!5m2!1sen!2sus', CAST(40.050294 AS DECIMAL(10,6)), CAST(-82.418891 AS DECIMAL(10,6))),
('Little Fish Brewing Company', '8675 Armitage Rd, Athens, OH 45701', 2015, 'Little Fish Brewing Company in Athens, Ohio, crafts small-batch beers with local ingredients, offering a delightful range from hoppy ales to rich stouts. Their taproom welcomes you to taste Athens in every sip.', 'https://lh3.googleusercontent.com/K7J8W7j2RkXv9neXhhSlE9MfU5voTMTCDGdyGLvUILYNgX9S_prZj8s8SLtU5SWg9h4NJB8PwxJ7AFnqYhRlfel7grCb=s150', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d789506.6091273183!2d-82.59179465393082!3d39.378646086177135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8848747797a8a283%3A0x381494aa334b7823!2sLittle%20Fish%20Brewing%20Company!5e0!3m2!1sen!2sus!4v1713399887711!5m2!1sen!2sus', CAST(39.374399 AS DECIMAL (10,6)), CAST(-82.144101 AS DECIMAL(10, 6))),
('Yellow Springs Brewery Taproom & Kitchen', '2855 Indianola Ave, Columbus, OH 43202', 2013, 'At Yellow Springs Brewery, we brew exceptional beer every day in every batch. Founded in 2013, today we produce multiple core and packaged brands along with dozens of innovative seasonal beers.','https://images.squarespace-cdn.com/content/v1/65410d79866d2b6c0256f373/4ec291e9-a251-4413-8796-008bcdce9524/Yellow-Springs-Brewery-Logo-Full-Color.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3055.404512127875!2d-83.00316033572078!3d40.021747170855136!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388d78793b1de7%3A0xd31edb4b5a2ad7a!2sYellow%20Springs%20Brewery%20Taproom%20%26%20Kitchen!5e0!3m2!1sen!2sus!4v1713401034271!5m2!1sen!2sus', CAST(40.021969 AS DECIMAL(10,6)), CAST(-83.002302 AS DECIMAL(10,6))),
('Parsons North Brewing Company', '685 Parsons Ave, Columbus, OH 43206', 2008, 'A small craft brewery adjacent to Downtown Columbus with a wide variety of beer styles.' ,'https://media.racecheck.com/EventInstance/922fbac9-450a-41b5-9f96-5444a2ec9fe6.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12234.48159290136!2d-82.99302183603814!3d39.949879944292285!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x883889fa468b5481%3A0x43c9b00573da795e!2sParsons%20North%20Brewing%20Company!5e0!3m2!1sen!2sus!4v1713401483182!5m2!1sen!2sus', CAST(39.950505 AS DECIMAL(10,6)), CAST(-82.982679 AS DECIMAL(10,6))),
('Homestead Beer Company', '811 Irving Wick Dr W, Heath, OH 43056', 2011, 'What started with a single taproom in Heath now includes the best hang in Uptown Marysville, the heartbeat of Canal Winchester, and multiple places for you to get some of the best beer in Ohio.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWYPfeflRiHBDFBEyLKMmsZhp2vQfwFI5KmwDPrSKgCg&s', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1564137.0934203053!2d-84.23986752166141!3d40.031778302955196!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8838167fbf9ed3ed%3A0x44849a244df7daa5!2sHomestead%20Beer%20Company!5e0!3m2!1sen!2sus!4v1713402435496!5m2!1sen!2sus', CAST(40.313001 AS DECIMAL (10, 6)), CAST(-83.369201 AS DECIMAL(10, 6))),
('Warped Wing Brewing Company', '26 Wyandot St, Dayton, OH 45402', 2014, 'Our original Taproom & full-scale production brewery opened in January of 2014. Located in the heart of downtown Dayton, Ohio – it’s the former site of the Buckeye Brass & Iron Foundry circa 1938.', 'https://shop.warpedwing.com/wp-content/uploads/sites/2/2023/04/ww_red_round_sticker-1.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d392590.480707738!2d-84.46627476718751!3d39.759568299999984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x884083fdf6b21d23%3A0xacf318afa97eeb82!2sWarped%20Wing%20Brewing%20Company!5e0!3m2!1sen!2sus!4v1713402813534!5m2!1sen!2sus', CAST(39.779623 AS DECIMAL(10,6)), CAST(-84.184063 AS DECIMAL(10,6))),
('Zaftig Brewing Co & Taproom', '7020 Huntley Rd # A, Worthington, OH 43229', 2013, 'Zaftig Brewing Company is Worthingtons only craft brewery, offering an extensive array of selections. Well-known in Columbus for our high-gravity, full-bodied ales, we arent afraid to push the boundaries of what great craft beer can be.', 'https://www.nnemappantry.org/wp-content/uploads/2020/10/Zaftig-aluminum-sign-PNG.png', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7258.023668022042!2d-83.00196608729844!3d40.106116743317166!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8838f353f7748f85%3A0xb62eb0b3e65c97e5!2sZaftig%20Brewing%20Co%20%26%20Taproom!5e0!3m2!1sen!2sus!4v1713403217572!5m2!1sen!2sus', CAST(40.106448 AS DECIMAL(10,6)), CAST(-82.997640 AS DECIMAL(10,6)));

-- INSERT beer
INSERT INTO beer (name, brewery_id, style, abv, ibu, description, imageURL) VALUES
('$60 Nachos', 1, 'Double IPA', 8.0, 80, 'Intensely hoppy ale with a bold bitterness and tropical fruit flavors.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('$120 Nachos', 1, 'Triple IPA', 12, 80, 'Triple Dry-Hopped Triple IPA with Citra Hops', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/imperial-india-pale-ale.jpg'),
('Fitness Freak', 1, 'Berliner Weisse', 4.0, 5, 'Tart and refreshing wheat beer with a clean, crisp finish.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/berliner-style-weisse.jpg'),
('Belloq', 1, 'Stout with Coffee and Vanilla', 4.2, 10, 'Smooth caramel & chocolate notes get a massive coffee rogering. Competitively intellectual flavor that makes you feel smarter than you look.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/coffee-beer.jpg'),
('Club Paradise', 1, 'Sour Ale', 8, 20, 'Our Rotating Tiki Cocktail Inspired Sour IPA brewed with Fruit Purée, Vanilla & Milk Sugar', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/honey-beer.jpg'),
('Are we Having Fun Yet?', 1, 'American Pale Ale', 6, 35, 'Double dry-hopped with Belma, Citra & Mosaic, this pillowy soft ale delivers massive notes of strawberry, melon & papaya.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/english-style-pale-ale-esb.jpg'),

('Dire Wolf', 2, 'Porter', 10.5, 35, 'Smooth and velvety ale with notes of roasted malt, dark chocolate, and a hint of smoke.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/robust-porter.jpg'),
('Daybreak', 2, 'Coffee Vanilla Cream Ale', 5, 14, 'Light-bodied brilliant clarity iced coffee beer.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/coffee-beer.jpg'),
('Wolfs Ridge Brewery IPA', 2, 'American IPA', 6.8, 70, 'This year-round unfiltered American IPA is all about the hops in every way. Layered hopping techniques provide a perfect balance of hop flavor, aroma, and bitterness, ranging from tropical citrus fruit to hints of sticky pine.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('Hazy IPA', 2, 'Hazy IPA', 6.5, 25, 'Our new core Hazy IPA is all about the hops, featuring Simcoe and Mosaic for classic citrus and pine flavors, as well as late-addition Cryo Amarillo for an extra aromatic punch of tropical fruit and berry. A soft, pillowy mouthfeel keeps our Hazy from imparting too much lingering bitterness, a perfectly balanced brew to enjoy for any occasion, any time of year!', 'http://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/new-england-ipa.jpg'),
('Walking Taco', 2, 'Mexican-style Lager with Lime', 4.5, 9,'A classic Mexican brew gets the Midwestern treatment! Like tasty tacos crunched up in your favorite bag of chips, our Mexican-style lager with lime is sure to be a crushable crowd pleaser for any occasion. Whether you’re on the go or posted up on a patio, there’s nothing like a Walking Taco!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/german-style-kolsch.jpg'),
('Dream Boat', 2, 'Oatmeal Stout', 5.2, 21, 'How do you make a "dreamy" stout?  Just add oats! We took a classic stout recipe and brewed it with 800 lbs of flaked oats, providing an ultra creamy body and smooth mouthfeel. Rich flavors of bakers chocolate and coffee will gently float along your palate; one sip is all it takes to fall in love!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/irish-style-dry-stout.jpg'),

('Knotty Pine Amber Ale', 3, 'Amber Ale', 5.5, 20, 'A moderate, hoppy beer with a distinct caramel malty flavor.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-amber-lager.jpg'),
('Knotty Pine Jays', 3, 'German Pils', 4.5, 10, 'Light, crisp, maltiness and a clean heady finish are just a taste of what to expect from "Jays" German Lager', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/vienna-style-lager.jpg'),
('Knotty Pine Drip So Hard', 3, 'American Porter', 5.8, 35, 'The "Drip so Hard" Coffee Porter is a smooth drinking porter with an abundance of coffee notes throughout and a delicious chocolate finish.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/smoke-porter.jpg'),
('Knotty Pine Seren-DIPA-ty', 3, 'Double IPA', 8.2, 20, 'An intensely hoppy pale ale with minimal malt character, designed to showcase its strong hop flavors.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/imperial-india-pale-ale.jpg'),
('Knotty Pine Lite', 3, 'American Lite Lager', 5, 10, 'A low calorie and a low alcohol craft brew thats light tasting and perfect game day drinking.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/session-beer.jpg'),
('Knotty Pine One More', 3, 'American Pale Ale', 4.5, 10, 'A moderate, refreshing ale with noticeable hop aroma balanced by supporting malt flavors.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/english-style-pale-ale-esb.jpg'),

('Wild Card Saison', 4, 'Saison', 6.1, 25, 'Wild Card is a hazy pale orange French farmhouse style ale brewed with a kiss of cardamom. Calais yeast produces fruity, peppery esters that play well with the piney, fruity spice,', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/honey-beer.jpg'),
('Imperial Stout', 4, 'Stout', 7.6, 35, 'Dark and roasty ale with flavors of coffee, chocolate, and a hint of smoke.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/specialty-beer.jpg'),
('Bourbon Meyer Buckeye Stout (Tulip)',  4, 'Stout', 9.6, 40, 'BMBS starts with our Russian Imperial Stout at its base. We age it in wet bourbon barrels and add organic cacao nib and peanut butter.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/specialty-beer.jpg'),
('Rye Eye Eye IIPA', 4, 'Double IPA', 8.2, 15, 'This golden Double IPAs mash bill includes a copious amount of American rye, which contributes notes of spice and dill. The bulk of the mash is Pale Ale malt from Montana with a smidgen of toasted malt to emphasize the bready malt flavor.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/imperial-india-pale-ale.jpg'),
('Hazy Odyssey', 4, 'Juicy/ Hazy IPA', 6, 15, 'Barleys take on the juicy/hazy IPA that has a pleasant hop profile evoking flavors of mango and pineapple with a slight bitterness that is mellowed by the addition of lactose.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/california-common.jpg'),
('Frost Hop Cold IPA', 4, 'Crisp IPA', 7.4, 10, 'This super crisp IPA is piney, spicy, and bursting with citrus. Liam, Barleys Assistant Brewer, suggested we brew our first Cold IPA and include resinous Chinook hops paired with Citra and Mosaic.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),

('Bodhi', 5, 'Double IPA', 8.5, 80, 'Bodhi is a classic double IPA from Columbus Brewing Company, known for its bold hop flavors and citrusy aroma.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/imperial-india-pale-ale.jpg'),
('Creeper', 5, 'Imperial Stout', 10.2, 65, 'Creeper is a rich and robust imperial stout brewed by Columbus Brewing Company, featuring notes of chocolate, coffee, and caramel.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/chocolate-beer.jpg'),
('Devils Kush', 5, 'IPA', 6.66, 15, 'The king of the dank side—Devils Kush brings the hops through a blend of Pacific Northwest hops including Simcoe, Idaho 7, Strata and Chinook. It is intensely hoppy with subtle notes of citrus and tropical fruit backed up by a sinister 6.66% ABV.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('Columbus Lager', 5, 'Lager', 4.6, 18, 'Columbus Lager is an instant classic. The 2022 World Beer Cup Bronze winner pours with a timeless, bright golden hue with a lofty white head. A clean and crisp beer with each element working in perfect harmony, which retains the history and tradition of the style.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/german-style-kolsch.jpg'),
('Nug Wizard', 5, 'Experimental IPA', 7.6, 22, '5 nugs to rule them all! Nug Wizard is a magical brew featuring a 5-hop alchemy of experimental varieties that rain down notes of citrus and stone fruit.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('Margarita Playa', 5, 'Tart Ale with Lime and Salt', 4.6, 7, 'A refreshing, tart ale to put you in vacation mode. Every sip of Margarita Playa tastes like the perfect beach day with aromas of freshly-squeezed margarita and salty ocean air. Brewed with lime concentrate and salt, it resembles the bright sunshine and refreshes your taste buds.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/vienna-style-lager.jpg'),

('Susie', 6, 'New England IPA', 7, 37, 'Juicy hazy New England IPA with prominent notes of grapefruit', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/new-england-ipa.jpg'),
('Belgian Aloha', 6, 'Belgian Tripel', 9.6, 28, 'Brewed with Hibiscus with a floral flavor reminiscent of rose wine. 2019 Ohio Craft Brewers Cup Medal Winner', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/belgian-style-quadrupel.jpg'),
('Alum Creek', 6, 'Beach Blonde', 5.4, 27, 'Refreshing and crisp Blonde Ale. Perfect for a hot day or casual drinking.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/belgian-style-saison.jpg'),
('Dustys Done Deal', 6, 'Double New England IPA', 9.2, 47, 'Delicious hazy IPA that is light in flavor and body. Careful this ones sneaky.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/new-england-ipa.jpg'),
('Roosevelt Coffee Stout', 6, 'Coffee Stout', 5.5, 20, 'This beer is light in body and brewed with Olentangy River Brewing Companys cold brew concentrate. *Does contain a bit of caffiene.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-imperial-stout.jpg'),
('Ol n Tangy Classico', 6, 'Gose', 4.8, 25, 'A crisp tart sour brewed with salt made to be very refreshing. One that you can always come back to.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-sour.jpg'),

('Anchors Up', 7, 'California Common', 5.2, 37, 'SET SAIL! Biscuit & Caramel with herbal & minty hops. LEGENDARY!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/california-common.jpg'),
('Bolt', 7, 'Golden Ale', 5.8, 19, 'ELECTRIC! Light, Crisp and Refreshing. TAKE CHARGE!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/honey-beer.jpg'),
('Arise', 7, 'American IPA', 6.7, 66, 'FIND PASSION! Abundant Citrus and Tropical Fruit. RISE UP!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('Starseed', 7, 'Hazy IPA', 6.8, 42, 'DEFY GRAVITY! Tropical and Citrus Atoms Collide. WELCOME TO THE STARS!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/belgian-style-saison.jpg'),
('Midnight Ride', 7, 'American Stout', 6.5, 40, 'SADDLE UP! A Bold Blend of Dark Chocolate and Coffee Notes. DRINK THE MOON!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/irish-style-dry-stout.jpg'),
('Blackbird', 7, 'Blackberry Wheat', 5.56, 20, 'STAY CALM and BRAMBLE ON!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/belgian-style-wit.jpg'),

('Proliferous', 8, 'Double IPA', 8.3, 26, '','https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('Seventh Son', 8, 'Strong Ale', 7.7, 33, '', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/belgian-style-golden-strong-ale.jpg'),
('Kitty Paw', 8, 'Hard Seltzer', 4.2, 0, '', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/german-style-schwarzbier.jpg'),
('Assistant Manager', 8, 'Golden Ale', 5.2, 22, '', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/blonde-ale.jpg'),
('The Scientist', 8, 'IPA', 7, 27, '', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('Oubliette', 8, 'Imperial Stout', 12, 33, '','https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/specialty-beer.jpg'),

('Super Fantastic', 9, 'American IPA', 7, 60, 'The OG of DankHouse. This was the second recipe we ever created in our garage, and the only recipe we continue to brew today. This one is dry hopped with Amarillo, Mosaic, and Simcoe.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('Sour Files #3', 9, 'Fruited Sour', 6, 23, 'This one is fruited with raspberry, blackberry, blue raspberry, grape, lemonade, and vanilla.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/berliner-style-weisse.jpg'),
('Digi Digi Digi', 9, 'Hazy Triple IPA', 10, 65, 'In the words of the great Rza.......Hoppy Hoppy Hoppy, Digi Digi Digi. Your a** will be stuck on this beer like a Victoria Secret wedgie. We dry hopped this one with Citra, Strata, and Nectaron.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/new-england-ipa.jpg'),
('Annie, Are You Ok?', 9, 'Red Ale', 5, 33, 'As smooth as that mans moonwalk! A nice and simple easy drinking red ale.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/irish-style-red.jpg'),
('Kusch Light ', 9, 'Light Lager', 4.2, 15, 'Welcome to the home of Kusch Light, the coldest and smoothest light lager there is. Here at DankHouse we’re serious about cracking a cold one and heading for the disc golf course.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/german-style-kolsch.jpg'),
('Clear Eyes', 9, 'American IPA', 6.5, 25, 'We took a new, fresh, clear headed (that part might be a stretch) approach to our American/West Coast IPAs for this one. Crystal clear in appearance and dry hopped with Citra, Mosaic, and Eureka!.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),

('Ridge Runner Lil Harveys', 10, 'Nitro Milk Stout', 5.5, 22, 'Nitro Milk Stout with locally-roasted Ridge Runner coffee. Our buddy Pat Balding roasts organic coffee under the name Ridge Runner Coffee.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-stout.jpg'),
('Woodthrush', 10, 'Farmhouse Biere De Garde', 6.5, 20, 'It is a malty but dry farmhouse ale with a light spicing of coriander, lemon peel, and grains of paradise.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/biere-de-garde.jpg'),
('Dear Science', 10, 'Hazy IPA', 6.5, 45, 'Dear Science was the first hazy I.P.A. we brewed at Little Fish that uses a special strain of yeast, which was experimental at the time, but is now commonly accepted in the world of craft brewing.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/belgian-style-saison.jpg'),
('Smoked Helles', 10, 'Beechwood-Smoked Light Lager', 5.3, 30, 'Smoked Helles is a crisp, light lager with a moderate to intense (depending on your tolerance level) beechwood smoke character.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/vienna-style-lager.jpg'),
('Pinch Guey', 10, 'Barrel-aged Mexican Chocolate Imperial Stout', 13.5, 20, '2023s batch is a blend of imperial milk stout, aged in Heaven Hill and Basil Hayden bourbon barrels for 18 months. After blending, it was infused with whole cacao nibs,vanilla beans, ancho chiles, chile de arbol, and Cassia cinnamon.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/specialty-beer.jpg'),
('Abseil Pils', 10, 'Pilsner', 5.5, 14, 'Weyermann Barke Pilsner malt, and fermented cold with our preferred lager strain. Flavor Profile: Everything a German pils should be: elegant, simple, eminently drinkable.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/german-style-kolsch.jpg'),

('Boat Show', 11, 'IPA', 7, 10, 'Juicy tropical fruit and citrus notes blaze through this fresh and hoppy American IPA. It’s an IPA that drinks more like a strong pale ale. There is a low level of bitterness.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-pale-ale.jpg'),
('Creative Space', 11, 'Hazy IPA', 6.7, 43, 'Made with Citra, Mosaic, and Amarillo hops, this hazy IPA has an assertive citrusy brightness with some tropical fruit undertones. A couple pints of this juicy goodness will get your creative juices flowing!', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/new-england-ipa.jpg'),
('Captian Stardust', 11, 'Saison', 6.5, 33, '', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/belgian-style-saison.jpg'),
('Springer', 11, 'Golden Ale', 5.4, 15, '', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/blonde-ale.jpg'),
('Handsome', 11, 'American Brown', 5.5, 27, '', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-brown-ale.jpg'),
('MultiBall', 11, 'Pilsner', 5.5, 12, '', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/german-style-kolsch.jpg'),

('Barrel Sour Hugus Cider', 12, 'Local Cider', 6.9, 22, '2021 Hugus Farms Local Cider', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/belgian-style-saison.jpg'),
('Passionfruit Mango Gose', 12, 'Passionfruit Mango Gose', 6.5, 17, 'Tart, Crisp, and Tropical', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/english-style-bitter.jpg'),
('Tropical East Coast IPA', 12, 'Tropical East Cost IPA', 6, 27, 'Citrus, Pineapple, Juicy', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/english-style-pale-ale-esb.jpg'),
('Mexican Lager', 12, 'Mexican Lager', 5, 10, 'Light, Smooth, and Full', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/german-style-helles.jpg'),
('Kolsch', 12, 'Kolsch', 5, 12, 'Crisp, Dry, and Light', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/german-style-kolsch.jpg'),
('East Coast IPA', 12, 'East Coast IPA', 7.2, 32, 'Tropical, Juicy, and Smooth', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/new-england-ipa.jpg'),

('Tenpenny Amber', 13, 'Amber Ale', 5.4, 36, 'Balances sweet, caramel malt with a mildly bitter, fragrant hop nose. Underneath those flavors lurks a powerhouse yeast that contributes the classic ale ester profile rather than the too clean flavors in modern beer.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/irish-style-red.jpg'),
('Galactic Heroes', 13, 'IPA', 7.2, 22, 'Erupting with West Coast IPA notes of grapefruit, juicy orange and lemon, this towering beer lays it down thick and heavy without being a palate wrecker.', 'https://www.craftbeer.com/wp-content/themes/craftbeer2023/images/icons/beer_target.png'),
('Snake Oil', 13, 'IPA', 7.5, 27, 'We crafted this beer as the more accessible little brother to 3 MC’s with a similar hop and grain bill and using the same yeast. ', 'https://www.craftbeer.com/wp-content/themes/craftbeer2023/images/icons/beer_target.png'),
('Sun-Kissed Wheat', 13, 'American Wheat', 5.4, 23, 'We started with a giant dose of wheat, a tiny smattering of hops and a classic American Hefeweizen yeast – to match those mild notes we brought along a huge helping of citrus peel and coriander.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-style-wheat-wine-ale.jpg'),
('Pioneer Pilsner', 13, 'Pilsner', 4.7, 14, 'The Germans have as many variations on the Pilsner as we do on the IPA and this one is a real classic – designed to conform to the Reinheitsgebot this Pilsner starts bitter and finishes clean.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/contemporary-gose.jpg'),
('Station Master', 13, 'Session IPA', 4.4, 31, 'A light, drinkable Session IPA, brewed clean and crisp with a shattering bitter and giant nose. You will sacrifice nothing but the hangover when you go session.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),

('Trotwood Lager', 14, 'Lager', 4, 9, 'Fireflies flash. Crickets hum. And the campfire, around which you and your companion sit, crackles and smokes. You watch the plumes, as they slip through the arms of old-growth trees, and vanish into an expanse of ancient stars.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/european-style-export.jpg'),
('Gamma Bomb', 14, 'IPA', 7.2, 96, 'Gamma Bomb IPA. A piney India Pale Ale. Exploding with hoppy goodness. Pull the pin.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg'),
('Radio Vision', 14, 'Hazy IPA', 6, 10, 'Can you see it? Can you hear it? Cut through the static and let the radio waves of Citra, Mosaic, Cascade, and Bravo hops transmit you to a hazy place filled with juicy, tropical flavors. Look. Listen. Tune in. RadioVision.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/imperial-india-pale-ale.jpg'),
('Flyer Red', 14, 'American Lager', 4.5, 12, 'Where the American spirit lives on. Flyer Red. An American Red Lager. A refreshingly smooth, patiently-fermented beer. Good things come to those who wait.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/california-common.jpg'),
('Flylight', 14, 'Lager', 4, 10, 'A solid, easy-to-drink, classic light beer. The kind that’s always in your fridge, because you know it’s good. Best enjoyed with your best buds. Fly Light Lager. Let it Fly.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/california-common.jpg'),
('Plane ole Pilsner', 14, 'Pilsner', 5.4, 30, 'Ohio. The heart of it all. The Buckeye State. And the TRUE birthplace of aviation. Take flight with a Plane ol’ Pils. But make no mistake, there‘s nothing “plane” about this pale lager.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/vienna-style-lager.jpg'),

('Mini Bomb Blonde', 15, 'Blonde Ale', 5, 25, 'Crisp, refreshing, and smooth with cereal malts; Mini Bomb is light and approachable, while not being overly hoppy, Subtle floral notes and unassuming citrus are present, but no one flavor dominates. The finish is soft, pleasant, and round. clean.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/blonde-ale.jpg'),
('Cart Path Kolsch', 15, 'Kolsch', 4.5, 17, 'Expertly hopped with Cascaxde and Amarillo, this inspired ale pays homage to its German roots while being uniquely American.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/european-style-export.jpg'),
('Hazy Miss Daisy', 15, 'New England IPA', 7, 54, 'Our traditional New England IPA boasts a tart juiciness derived from Amarillo and Mosaic hops. Featuring an inviting floral nose, Miss Daisy has noted of lemon and stone fruit with slight maltiness.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/new-england-ipa.jpg'),
('Cats in Space', 15, 'Double IPA', 10, 45, 'Crazy amounts of pineapple and mango haze with subtle pine and fruity esters send this double dry-hopped NEIPA into orbit.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/imperial-india-pale-ale.jpg'),
('Peach Please', 15, 'Kolsch', 4.5, 12, 'Infused with peach puree and expertly hopped with Cascade and Amarillo, the flavor is fruity, bright, with subtle notes of lemon.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/european-style-export.jpg'),
('Too Can', 15, 'Imperial IPA', 13, 38, 'The Imperial has a ridiculous amount of grain and an absurd amount of Centennial, Columbus, and Cascade hops which make for an ale that is full-bodied, but well-proportioned.', 'https://www.craftbeer.com/wp-content/uploads/_SF/thumbnails/american-india-pale-ale.jpg');


INSERT INTO reviews (beer_id, reviewer, review, rating) VALUES
(1, 'HopHead87', 'As a dedicated hop lover, I was eager to try the $60 Nachos Double IPA, and it did not disappoint!', 4.0),
(1, 'TheHoppyEnding', 'The taste follows suit, with a bold hoppy flavor that is balanced by a smooth malt backbone. It is refreshing and satisfying, perfect for a sunny afternoon.', 4.0),
(1, 'SourAleSipper67', 'The aroma is almost non-existent, with a faint hint of stale grains. The taste is equally lackluster, with no discernible flavor other than a vague sweetness that quickly fades into nothingness. Save your money and skip this one.', 1.0),
(2, 'BrewEnthusiast92', 'It pours a murky yellow with an off-putting aroma of spoiled fruit and wet cardboard.', 1.0),
(2, 'BeerlyBeloved', 'It is dangerously drinkable for its ABV, and I can not help but savor every sip.', 5.0),
(2, 'AleInWonderland', 'This beer pours a deep mahogany with a creamy tan head. The aroma is a heavenly blend of roasted malts and sweet vanilla, inviting you in for a sip.', 5.0),
(3, 'SourAleSipper67', 'Fitness Freak is a beer lovers dream come true!', 3.0),
(3, 'HopsAndDreams', 'While I appreciate a good funky beer, this one misses the mark entirely.', 2.0),
(3, 'BeerlyBeloved', 'The aroma is rich and roasty, with hints of chocolate and coffee. The taste is equally impressive, with layers of dark chocolate, espresso, and a subtle bitterness that balances it all out.', 1.0),
(4, 'CraftyDrinker22', 'There is no balance or nuance here, just a blunt taste of bitterness. I would not recommend this beer to anyone.', 2.0),
(4, 'BrewedAwakening', 'Tropical Thunder IPA is a tropical explosion of flavor!', 4.0),
(4, 'AleInWonderland', 'It is like drinking a glass of vinegar mixed with old gym socks. Avoid at all costs.', 2.0),
(5, 'AleGator', 'Club Paradise is a delightful blend of tropical flavors that transport you to a sunny beachside retreat.', 4.0),
(5, 'PintSizedLad', 'Cheers to a beer that brings a taste of paradise wherever you are!', 5.0),
(6, 'HoppyGoLucky11', 'The combination of Belma, Citra, and Mosaic hops brings out notes of strawberry, melon, and papaya, which is enjoyable but not mind-blowing.', 3.0),
(6, 'AleGator', 'While the beer is pleasant enough to enjoy casually, it does not quite deliver the boldness and complexity I look for in this style.', 3.0),

(7, 'LagerMcLovin97', 'This beer should come with a warning label: May induce gag reflex. It is a crime against taste buds everywhere.', 1.0),
(7, 'BrewedAwakening', 'I have had better beverages from a stagnant puddle. Drinking this beer was like licking the floor of a dive bar after a frat party.', 2.0),
(7, 'AleInWonderland', 'I have never been more disappointed in a beer in my life. It is like they bottled disappointment and labeled it as beer. I would rather drink my own tears than take another sip of this garbage.', 1.0),
(8, 'BeerlyBeloved', 'The light body and clarity were fine, but they could not compensate for the lack of flavor. Not terrible, but definitely not worth seeking out.', 3.0 ),
(8, 'Hoptimistic', 'Daybreak was a letdown from start to finish. The promise of a light-bodied iced coffee beer sounded intriguing, but the execution fell flat.', 2.0 ),
(8, 'LagerMcLovin97', 'I had high hopes for Daybreak, but it failed to deliver. The idea of combining coffee with beer sounded intriguing, but the reality was lackluster.', 2.0 ),
(9, 'BrewskiBear', 'The balance of flavors is spot on, with just the right amount of bitterness to keep things interesting.', 4.0),
(9, 'AleInWonderland', 'Impressive IPA from Wolfs Ridge Brewery! This beer showcases a masterful blend of hop flavors and aromas. From the tropical citrus notes to the subtle undertones of pine, each sip is a journey of flavor.', 4.0),
(9, 'BrewedAwakening', 'It is refreshing enough to enjoy on a hot summer day yet complex enough to satisfy even the most discerning palate. Well done!', 4.0),
(10, 'BarleyQuinn', 'It is refreshing, flavorful, and perfect for those who enjoy a hop-forward brew.', 4.0),
(10, 'Brewbacca', 'The combination of Simcoe and Mosaic hops gives it a vibrant citrus character with just the right amount of piney bitterness. ', 3.0),
(10, 'LagerMcLovin97', 'It is smooth, juicy, and incredibly drinkable. Definitely worth trying for those seeking a well-crafted IPA experience.', 4.0),
(11, 'SourAleSipper67', 'Perfect for any occasion, from a day at the beach to a backyard barbecue. A definite crowd-pleaser that deserves a spot in every beer lovers fridge!', 5.0),
(11, 'BarleyQuinn', 'Walking Taco never disappoints. I can not get enough of its refreshing flavor and crushable appeal. Five stars all around for this delicious brew!', 5.0),
(12, 'LagerMcLovin97', 'While the flavors of bakers chocolate and coffee are present, they lack the depth and richness I expect from a stout of this style.', 2.0),
(12, 'Brewbacca', 'It is a good choice for those seeking a straightforward stout, but it falls short of being truly memorable.', 2.0),
(12, 'SourAleSipper67', 'It is enjoyable enough for a casual sip, but it does not quite reach the level of excellence I was hoping for.', 3.0),

(13, 'Brewbacca', 'Knotty Pine Amber Ale hits the mark with its balance of hoppy bitterness and caramel malt sweetness. The flavors complement each other nicely, creating a beer that is both refreshing and satisfying.', 5.0 ),
(13, 'AleInWonderland', 'Whether you are a seasoned beer enthusiast or just looking to try something new, this beer will not disappoint.', 3.0 ),
(13, 'Hoptimistic', 'The caramel malty flavor adds a nice richness to the beer, while the hoppy notes provide a pleasant bitterness that keeps things interesting. ', 5.0 ),
(14, 'Brewbacca', 'Do yourself a favor and steer clear unless you enjoy disappointment in a bottle.', 1.0),
(14, 'BarleyQuinn', 'Knotty Pine Jays German Lager did not quite live up to its promise. While it is certainly refreshing with its light and crisp profile, the maltiness was disappointingly subdued.', 2.0),
(14, 'LagerMcLovin97', 'While it may appeal to those who prefer a lighter lager, it did not leave a lasting impression on my palate.', 2.0),
(15, 'BrewskiBear', 'Knotty Pine Drip So Hard is a true gem in the world of porters. Its rich coffee aroma draws you in, while the smooth, velvety texture and subtle chocolate undertones keep you coming back for more. A deliciously satisfying brew!', 4.0),
(15, 'BarleyQuinn', 'Smooth on the palate, it offers a comforting warmth with each sip. A perfect choice for those cozy nights by the fire.', 3.0),
(15, 'BeerlyBeloved', 'Congratulations to the brewery for creating a beer that manages to offend every sense. It smells like a skunks backside, tastes like regret, and leaves a lingering aftertaste of despair.', 1.0),
(16, 'AleInWonderland', 'This beer is a masterpiece of brewing. It is flawless in every way.', 5.0),
(16, 'TheBeerdedOne', 'This beer exceeded my expectations. It is flavorful, refreshing, and just plain good. While it may not be the most adventurous beer out there, it is definitely one I would consider a staple in my fridge.', 4.0),
(17, 'LagerMcLovin97', 'I am in beer heaven! This brew is an absolute masterpiece.', 4.0),
(17, 'SourAleSipper67', 'This beer falls squarely in the middle for me. It is not terrible, but it is not great either. It is just sort of... there.', 3.0),
(17, 'TheBeerdedOne', 'I had heard good things about this beer, but it failed to impress. The flavor was weak, and it lacked the boldness I expect from a quality brew.', 2.0),
(18, 'BarleyQuinn', 'If I wanted to experience the taste of pure misery, I would just lick the underside of a dumpster. ', 1.0),
(18, 'AleInWonderland', 'This beer is a masterpiece of brewing. It is flawless in every way.', 4.0),
(18, 'LagerMcLovin97', 'It had a strange bitterness that lingered unpleasantly, ruining the entire drinking experience.', 1.0),

(19, 'Brewbacca', 'Simply perfection in a glass.', 5.0 ),
(19, 'TheBeerdedOne', 'I have never been more disappointed in a beer in my life. It is like they bottled disappointment and labeled it as beer. I would rather drink my own tears than take another sip of this garbage.', 1.0 ),
(19, 'BarleyQuinn', 'If you are looking for something unremarkable to sip on, this could fit the bill.', 3.0 ),
(20, 'AleInWonderland', 'It is like they scraped the bottom of the barrel and bottled it. Do yourself a favor and avoid this dumpster juice at all costs.', 2.0 ),
(20, 'Brewbacca', 'It is like drinking a glass of vinegar mixed with old gym socks. Avoid at all costs.', 1.0 ),
(20, 'PintSizedLad', 'The flavor is exquisite, the aroma is mesmerizing, and the mouthfeel is like velvet on the tongue. It is the kind of beer that you want to savor and cherish every moment you have with it.', 5.0 ),
(21, 'AleInWonderland', 'I am in awe of this beer. It is a marvel of brewing, a testament to the skill and dedication of the brewmaster.', 4.0 ),
(21, 'BarleyQuinn', 'It is the kind of beer that leaves you speechless.', 4.0 ),
(21, 'Brewbacca', 'The flavor is like a burst of sunshine, the aroma is like a breath of fresh air, and the mouthfeel is like a hug from an old friend. It is the kind of beer that fills your soul with joy.', 5.0 ),
(22, 'LagerMcLovin97', 'Where has this beer been all my life? It is absolutely phenomenal! The flavor is rich and intense, the aroma is heavenly, and the mouthfeel is velvety smooth. It is like drinking liquid gold. I can not recommend it highly enough.', 5.0),
(22, 'AleInWonderland', 'This beer is decent, nothing more, nothing less. It is drinkable, but it did not leave a lasting impression. It is missing that special something that would make me want to reach for it again.', 3.0),
(23, 'TheBeerdedOne', 'Simply perfection in a glass.', 5.0),
(23, 'BeerlyBeloved', 'It is like drinking a glass of vinegar mixed with old gym socks. Avoid at all costs.', 1.0),
(23, 'LagerMcLovin97', 'I found this beer to be average overall. It did not blow me away, but it did not disappoint me either.', 3.0),
(24, 'BarleyQuinn', 'This beer is proof that sometimes the universe just wants to see you suffer. Drain pour material does not even begin to describe it.', 1.0),
(24, 'Brewbacca', 'It is the kind of beer that leaves you speechless.', 5.0),


(25, 'TheBeerdedOne', 'I have had better tasting medicine. Seriously, I would rather be sick than drink this again.', 1.0 ),
(25, 'BrewedAwakening', 'This beer was a complete letdown. The flavors were flat, and it tasted like it had been sitting on the shelf for way too long.', 2.0 ),
(25, 'Brewbacca', 'It is the kind of beer you might enjoy if you are not too picky, but it is not something I would go out of my way to buy again.', 2.0 ),
(26, 'TheBeerdedOne', 'This beer tasted like disappointment in a can. I would rather drink water from a ditch.', 1.0 ),
(26, 'AleInWonderland', 'This beer is a masterpiece of brewing. It is flawless in every way.', 5.0 ),
(27, 'BrewedAwakening', 'I had high hopes for this beer, but it fell short in every way. It lacked depth and character, and the aftertaste was downright unpleasant.', 2.0 ),
(28, 'Brewbacca', 'This beer is a masterpiece, plain and simple. It is the kind of beer that makes you grateful to be alive. The flavor is like a symphony for the taste buds, the aroma is like a love song for the senses, and the mouthfeel is like a warm embrace.', 5.0 ),
(29, 'AleInWonderland', 'This beer is a masterpiece of brewing. It is flawless in every way.', 4.0 ),
(29, 'LagerMcLovin97', 'I am blown away by this beer. It is absolutely incredible.', 4.0 ),
(30, 'BrewedAwakening', 'It is the kind of beer that leaves you speechless.', 5.0 ),
(30, 'Brewbacca', ' It had a strange bitterness that lingered unpleasantly, ruining the entire drinking experience.', 2.0 ),
(30, 'LagerMcLovin97', 'The flavor is out of this world, the aroma is like a dream, and the mouthfeel is like floating on a cloud. It is the kind of beer that changes lives.', 5.0 ),

(31, 'Brewbacca', 'This beer was a swing and a miss. It tasted stale and uninspired, like someone forgot to put in the effort to make it worth drinking.', 2.0 ),
(31, 'AleInWonderland', 'Drinking this beer was like a punishment from the universe for all my past sins. I would rather drink from a puddle in a back alley.', 1.0 ),
(32, 'SourAleSipper67', 'I am in beer heaven! This brew is an absolute masterpiece. The flavor is exquisite, the aroma is mesmerizing, and the mouthfeel is like velvet on the tongue.', 5.0 ),
(32, 'Brewbacca', 'It is the kind of beer that leaves you speechless.', 5.0 ),
(32, 'LagerMcLovin97', 'This beer is a masterpiece, plain and simple. It is the kind of beer that makes you grateful to be alive. The flavor is like a symphony for the taste buds, the aroma is like a love song for the senses, and the mouthfeel is like a warm embrace.', 5.0 ),
(33, 'TheHoppyEnding', 'Congratulations to the brewer for creating a beer that manages to simultaneously taste like regret and despair. Truly an achievement in failure.', 1.0 ),
(33, 'SourAleSipper67', 'I would rather drink a glass of spoiled milk than subject myself to another sip of this vile concoction.', 1.0 ),
(33, 'AleInWonderland', 'I am in awe of this beer. It is a marvel of brewing, a testament to the skill and dedication of the brewmaster.', 5.0 ),
(34, 'HopHead87', 'The flavor is like a burst of sunshine, the aroma is like a breath of fresh air, and the mouthfeel is like a hug from an old friend. It is the kind of beer that fills your soul with joy.', 5.0 ),
(35, 'Brewbacca', 'Tried this beer and immediately regretted every life choice that led me to that moment.', 1.0 ),
(35, 'LagerMcLovin97', 'This beer is hands down the best I have ever had. The flavor is mind-blowing, the aroma is intoxicating, and the mouthfeel is pure bliss. It is the kind of beer that you want to shout about from the rooftops. Five stars does not even begin to do it justice.', 5.0 ),
(36, 'BrewedAwakening', 'I do not know what went wrong with this beer, but it was undeniably bad. Save your money and choose something else from the fridge.', 3.0 ),
(36, 'AleInWonderland', 'I found this beer to be average overall. It did not blow me away, but it did not disappoint me either.', 3.0),

(37, 'TheBeerdedOne', 'If I wanted to experience the taste of pure misery, I would just lick the underside of a dumpster. At least then I would save some money.', 1.0 ),
(37, 'SourAleSipper67', 'This beer is a masterpiece of brewing. It is flawless in every way.', 5.0 ),
(38, 'LagerMcLovin97', 'Simply perfection in a glass.', 5.0 ),
(39, 'AleInWonderland', 'This beer did not really leave much of an impression on me. It is not bad, but it is not particularly memorable either. It is the kind of beer you might drink if it is offered to you, but you probably would not seek it out on your own', 3.0 ),
(39, 'TheBeerdedOne', 'This beer is decent, nothing more, nothing less. It is drinkable, but it did not leave a lasting impression. It is missing that special something that would make me want to reach for it again.', 3.0),
(40, 'SourAleSipper67', 'I am in awe of this beer. It is a marvel of brewing, a testament to the skill and dedication of the brewmaster.', 4.0 ),
(40, 'HopHead87', 'It is like drinking a glass of vinegar mixed with old gym socks. Avoid at all costs.', 1.0 ),
(40, 'LagerMcLovin97', 'I am in beer heaven! This brew is an absolute masterpiece. The flavor is exquisite, the aroma is mesmerizing, and the mouthfeel is like velvet on the tongue.', 5.0 ),
(41, 'TheBeerdedOne', 'It is like they brewed it in a cesspool.', 1.0 ),
(41, 'AleInWonderland', 'This beer is proof that sometimes the universe just wants to see you suffer. Drain pour material does not even begin to describe it.', 1.0 ),
(42, 'Brewbacca', 'If you are looking for something unremarkable to sip on, this could fit the bill.', 3.0 ),

(43, 'BrewedAwakening', 'It is the kind of beer that leaves you speechless.', 4.0 ),
(43, 'SourAleSipper67', 'I found this beer to be average overall. It did not blow me away, but it did not disappoint me either.', 3.0),
(43, 'LagerMcLovin97', 'Avoid like the plague unless you enjoy suffering.', 1.0 ),
(44, 'HopHead87', 'This beer is a masterpiece, plain and simple. It is the kind of beer that makes you grateful to be alive. The flavor is like a symphony for the taste buds, the aroma is like a love song for the senses, and the mouthfeel is like a warm embrace.', 5.0 ),
(44, 'BrewedAwakening', 'I am blown away by this beer. It is absolutely incredible.', 5.0 ),
(45, 'AleInWonderland', 'I would not even use this beer to clean my toilet.', 1.0 ),
(45, 'SourAleSipper67', 'Where has this beer been all my life? It is absolutely phenomenal! The flavor is rich and intense, the aroma is heavenly, and the mouthfeel is velvety smooth. It is like drinking liquid gold. I can not recommend it highly enough.', 5.0 ),
(45, 'HopHead87', 'I am in awe of this beer. It is a marvel of brewing, a testament to the skill and dedication of the brewmaster.', 5.0 ),
(46, 'BrewedAwakening', 'This beer is hands down the best I have ever had. The flavor is mind-blowing, the aroma is intoxicating, and the mouthfeel is pure bliss. It is the kind of beer that you want to shout about from the rooftops. Five stars does not even begin to do it justice.', 5.0 ),
(46, 'LagerMcLovin97', 'This beer is a slap in the face to anyone who appreciates quality brewing. I would rather drink my own sweat.', 1.0 ),
(46, 'AleInWonderland', 'It is like they brewed it in a cesspool.', 1.0 ),
(47, 'BrewedAwakening', 'Simply perfection in a glass.', 5.0 ),
(48, 'TheBeerdedOne', 'This beer is a masterpiece of brewing. It is flawless in every way.', 5.0 ),
(48, 'AleInWonderland', 'It is like drinking a glass of vinegar mixed with old gym socks. Avoid at all costs.', 1.0 );


INSERT INTO brewery_images (brewery_id, image_url) VALUES
(1, 'https://i.ytimg.com/vi/szglL4L4Zxw/maxresdefault.jpg'),
(1, 'https://resizer.otstatic.com/v2/photos/wide-huge/2/26171120.jpg'),
(1, 'https://cdn.columbusunderground.com/wp-content/uploads/2016/02/hoof-hearted-01.jpg'),

(2, 'https://media-cdn.tripadvisor.com/media/photo-s/15/73/f2/88/storefront.jpg'),
(2, 'https://i0.wp.com/ohiocraftbeer.org/wp-content/uploads/2015/11/Header_WolfRidge3.jpg?fit=800%2C533&ssl=1'),
(2, 'https://images.squarespace-cdn.com/content/v1/5eb095c59e8905404744a7b9/1600707117058-90FW815G1H57GZKLAONO/image-asset.jpeg'),

(3, 'https://i.ytimg.com/vi/IzW51YGN_Bs/hqdefault.jpg'),
(3, 'https://media-cdn.tripadvisor.com/media/photo-s/12/bb/79/3c/1524529469233-largejpg.jpg'),
(3, 'https://www.columbusmonthly.com/gcdn/authoring/2015/07/01/NCOA/ghows-OH-207953c2-bb9f-449a-992b-7ed533b559bf-943d0844.jpeg'),

(4, 'https://i0.wp.com/ohiocraftbeer.org/wp-content/uploads/2015/11/barleys_header2.jpg?fit=800%2C533&ssl=1'),
(4, 'https://www.scootersbars.com/wp-content/uploads/2016/07/1136_1.jpg'),
(4, 'https://popmenucloud.com/cdn-cgi/image/width%3D600%2Cheight%3D600%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/apxqvlfc/1d8bb0e8-0738-4967-b8ac-8a54718d2802.jpg'),

(5, 'https://breakfastwithnick.com/wp-content/uploads/cbc-beer-hall-13.jpeg'),
(5, 'https://breakfastwithnick.com/wp-content/uploads/cbc-beer-hall-8.jpeg'),
(5, 'https://images.squarespace-cdn.com/content/v1/5267e4e1e4b0cdd9f1919db3/1683730150399-U02R3NM6EFKG67RNZ93C/Bar+view.jpg'),

(6, 'https://media-cdn.tripadvisor.com/media/photo-s/1c/a1/e7/33/view-of-lovely-taproom.jpg'),
(6, 'https://www.oxstudioinc.com/wp-content/uploads/2019/01/20181211_ccs_orb_ext_428-2_hdr.jpg'),
(6, 'https://cdn7.localdatacdn.com/oh/lewis-center/4944215/original/k0g2y5yBn7.jpg'),

(7, 'https://ohio.org/static/uploads/0688y00000B9fWRAAZ.jpg'),
(7, 'https://patspints.files.wordpress.com/2023/10/psx_20231004_173134.jpg?w=1024'),
(7, 'https://thunderwingbrewing.com/wp-content/uploads/2023/10/Social.jpg'),

(8, 'https://images.squarespace-cdn.com/content/v1/51abeb0be4b08f6a770c06bf/1650313359131-8VZDS8MZODE3WUBB2QKC/DSCF3526.jpg'),
(8, 'https://images.squarespace-cdn.com/content/v1/51abeb0be4b08f6a770c06bf/1650313354278-V0THO8EZ1OVNRCJKM74P/DSCF2933.JPG'),
(8, 'https://www.columbusmonthly.com/gcdn/authoring/2016/03/30/NCOA/ghows-OH-ca7b932f-77fb-4c72-88f0-fbef83175097-3a284ac9.jpeg?width=1200&disable=upscale&format=pjpg&auto=webp'),

(9, 'https://cdn.columbusunderground.com/wp-content/uploads/2023/01/DankHouse1_DanWhalen.jpg'),
(9, 'https://i.ytimg.com/vi/hkxhBYEj4Tg/maxresdefault.jpg'),
(9, 'https://cdn.columbusunderground.com/wp-content/uploads/2023/01/DankHouse4_DanWhalen.jpg'),

(10, 'https://littlefishbrewing.com/wp-content/uploads/2022/11/LF-dayton-inside_crop-1024x576.jpg'),
(10, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6lEXd7oDDulm-hEgwmj8Ff7kRheEkGc1odg5O3avI1Q&s'),
(10, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcd-vVdTIuaSTMDqwYjNKKDsMTqGsCPhiKfA40quuN8w&s'),

(11, 'https://media.bizj.us/view/img/12641425/20231114085932.jpg'),
(11, 'https://cdn.columbusunderground.com/wp-content/uploads/2023/11/YellowSprings-9-SusanPost.jpg'),
(11, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS__uOZwdWDw8QwhEr73eUXCIguHlCQCcfOtIgOWJUv1w&s'),

(12, 'https://images.squarespace-cdn.com/content/v1/6387801772a9081a80bc7d24/1683936998270-LU1NQCUFVEACJACVZXPN/Lounge+Photo.jpg'),
(12, 'https://www.dispatch.com/gcdn/authoring/2019/01/15/NTWG/ghows-OH-dc33e557-4b96-416a-a082-299583a2d8d8-defcdb19.jpeg?crop=1899,1074,x0,y175&width=1899&height=1074&format=pjpg&auto=webp'),
(12, 'https://images.squarespace-cdn.com/content/v1/6387801772a9081a80bc7d24/1683936998270-6PA2L1784DAUG72ET56I/English+Ale+Pint.jpg'),

(13, 'https://cdn0.weddingwire.com/vendor/594211/3_2/960/jpg/a-range-of-great-tasting-beers_51_2112495-166479995411476.jpeg'),
(13, 'https://media.bizj.us/view/img/11502917/dsc0543-edit*1200xx7168-4032-0-377.jpg'),
(13, 'https://ahomesteadbrew.com/373074719_872478871168384_3406554451503842408_n.jpg'),

(14, 'https://ohio.org/static/uploads/0688y000004K5CZAA0.jpg'),
(14, 'https://cloudfront-us-east-1.images.arcpublishing.com/coxohio/BT5JMRVFPVBHVBJRYR7HKG6OWM.jpg'),
(14, 'https://cdn.craftbeer.com/wp-content/uploads/Warped-Wing-Taproom_Tara-Michael-1200x700.jpg'),

(15, 'https://media.bizj.us/view/img/7696962/zaftig-brewing-interior-dje*1200xx3093-2324-0-0.jpg'),
(15, 'https://pbs.twimg.com/media/ERucrn3XsAAbsR8?format=jpg&name=4096x4096'),
(15, 'https://ksr-ugc.imgix.net/assets/025/996/386/ba44818cf8d90877f26438af81508c6f_original.jpg?ixlib=rb-4.1.0&crop=faces&w=1024&h=576&fit=crop&v=1564649625&auto=format&frame=1&q=92&s=58d37de4ffa7fd271139858e2e7fa1dd');


COMMIT TRANSACTION;
